export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILURE = 'FETCH_GAME_FAILURE';

export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const START_GAME = 'START_GAME';
export const END_GAME   = 'END_GAME';

export const POST_PICK_REQUEST = 'POST_PICK_REQUEST';
export const POST_PICK_SUCCESS = 'POST_PICK_SUCCESS';
export const POST_PICK_FAILURE = 'POST_PICK_FAILURE';

export const FETCH_BEST_SCORES_REQUEST = 'FETCH_BEST_SCORES_REQUEST';
export const FETCH_BEST_SCORES_SUCCESS = 'FETCH_BEST_SCORES_SUCCESS';
export const FETCH_BEST_SCORES_FAILURE = 'FETCH_BEST_SCORES_FAILURE';
export const CLEAR_BEST_SCORES         = 'CLEAR_BEST_SCORES';

export const ADD_FLASH_ITEM    = 'ADD_FLASH_ITEM';
export const REMOVE_FLASH_ITEM = 'REMOVE_FLASH_ITEM';
